# Solstice FDE - guided credential setup
# Run it as many times as you like. It only asks for what is still missing,
# and it saves to .env immediately after every single paste.
#
#   powershell -ExecutionPolicy Bypass -File setup.ps1           # fill what's missing
#   powershell -ExecutionPolicy Bypass -File setup.ps1 -Status   # just show me what I have
#   powershell -ExecutionPolicy Bypass -File setup.ps1 -Force    # re-ask everything

param(
    [switch]$Status,
    [switch]$Force,
    [string[]]$Only   # e.g. -Only TELNYX_API_KEY   (re-asks just that one, even if already set)
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Definition
$envPath = Join-Path $root '.env'

# ---------------------------------------------------------------- field catalog

$fields = @(
    [pscustomobject]@{
        Key      = 'TELNYX_API_KEY'
        Label    = 'Telnyx API key'
        Where    = 'portal.telnyx.com  ->  API Keys  ->  Create API Key'
        Note     = 'One key covers voice, SMS and email. Starts with KEY'
        Pattern  = '^KEY'
        Secret   = $true
        Required = $true
    }
    [pscustomobject]@{
        Key      = 'ANTHROPIC_API_KEY'
        Label    = 'Anthropic API key'
        Where    = 'console.anthropic.com  ->  API Keys'
        Note     = 'Powers the chat brain. Starts with sk-ant-'
        Pattern  = '^sk-ant-'
        Secret   = $true
        Required = $true
    }
    [pscustomobject]@{
        Key      = 'SUPABASE_URL'
        Label    = 'Supabase project URL'
        Where    = 'supabase.com/dashboard  ->  your project  ->  Settings  ->  API'
        Note     = 'Looks like https://abcdefgh.supabase.co'
        Pattern  = '^https://.+\.supabase\.(co|in)$'
        Secret   = $false
        Required = $true
    }
    [pscustomobject]@{
        Key      = 'SUPABASE_ANON_KEY'
        Label    = 'Supabase anon key'
        Where    = 'same page, the key labelled  anon  public'
        Note     = 'Safe for the browser. Long token'
        Pattern  = '.{20,}'
        Secret   = $true
        Required = $true
    }
    [pscustomobject]@{
        Key      = 'SUPABASE_SERVICE_ROLE_KEY'
        Label    = 'Supabase service_role key'
        Where    = 'same page, the key labelled  service_role  (click Reveal)'
        Note     = 'Server side only. Never goes near the browser'
        Pattern  = '.{20,}'
        Secret   = $true
        Required = $true
    }
    [pscustomobject]@{
        Key      = 'NETLIFY_AUTH_TOKEN'
        Label    = 'Netlify personal access token'
        Where    = 'app.netlify.com  ->  User settings  ->  Applications  ->  Personal access tokens'
        Note     = 'Only needed if "netlify login" will not open a browser. Optional'
        Pattern  = '.{20,}'
        Secret   = $true
        Required = $false
    }
    [pscustomobject]@{
        Key      = 'DEMO_EMAIL'
        Label    = 'Demo email address'
        Where    = 'your own inbox'
        Note     = 'Where group proposals land during the demo'
        Pattern  = '^[^@\s]+@[^@\s]+\.[^@\s]+$'
        Secret   = $false
        Required = $true
    }
    [pscustomobject]@{
        Key      = 'DEMO_PHONE'
        Label    = 'Demo phone number'
        Where    = 'your mobile'
        Note     = 'Call transfer target and SMS recipient. Any format, I will tidy it'
        Pattern  = '^\+[1-9]\d{7,14}$'
        Secret   = $false
        Required = $true
    }
)

# Filled in automatically by Claude once the Telnyx key exists. Never prompted for.
$managed = @(
    'TELNYX_PUBLIC_KEY', 'TELNYX_ASSISTANT_ID', 'TELNYX_PHONE_NUMBER',
    'TELNYX_SIP_USERNAME', 'TELNYX_SIP_PASSWORD', 'TELNYX_EMAIL_FROM'
)
$flags = [ordered]@{ 'DEMO_MODE' = 'true'; 'AUTO_SEND' = 'false' }

# ---------------------------------------------------------------- helpers

function Read-EnvFile {
    $map = [ordered]@{}
    if (Test-Path $envPath) {
        foreach ($line in (Get-Content -LiteralPath $envPath -Encoding UTF8)) {
            if ($line -match '^\s*#') { continue }
            if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
                $map[$matches[1]] = $matches[2].Trim()
            }
        }
    }
    return $map
}

function Write-EnvFile($map) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('# Solstice FDE credentials. Never commit this file.')
    [void]$sb.AppendLine('# Generated by setup.ps1')
    [void]$sb.AppendLine('')
    foreach ($f in $fields) {
        $v = ''
        if ($map.Contains($f.Key)) { $v = $map[$f.Key] }
        [void]$sb.AppendLine("$($f.Key)=$v")
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('# Provisioned automatically by Claude')
    foreach ($k in $managed) {
        $v = ''
        if ($map.Contains($k)) { $v = $map[$k] }
        [void]$sb.AppendLine("$k=$v")
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('# Behaviour flags')
    foreach ($k in $flags.Keys) {
        $v = $flags[$k]
        if ($map.Contains($k) -and $map[$k] -ne '') { $v = $map[$k] }
        [void]$sb.AppendLine("$k=$v")
    }
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($envPath, $sb.ToString(), $utf8NoBom)
}

function Format-Masked($value, $isSecret) {
    if ([string]::IsNullOrWhiteSpace($value)) { return '(empty)' }
    if (-not $isSecret) { return $value }
    if ($value.Length -le 10) { return ('*' * $value.Length) }
    return ($value.Substring(0, 6) + ('*' * 6) + $value.Substring($value.Length - 4) + "  [$($value.Length) chars]")
}

function Format-Phone($raw) {
    $digits = ($raw -replace '[^\d]', '')
    if ($digits.Length -eq 10) { return "+1$digits" }
    if ($digits.Length -eq 11 -and $digits.StartsWith('1')) { return "+$digits" }
    if ($raw.Trim().StartsWith('+')) { return ($raw.Trim() -replace '[^\d+]', '') }
    return $raw.Trim()
}

# ---------------------------------------------------------------- status view

$values = Read-EnvFile

function Show-Status($map) {
    Write-Host ''
    Write-Host '  Credential status' -ForegroundColor Cyan
    Write-Host '  -----------------' -ForegroundColor Cyan
    $missing = 0
    foreach ($f in $fields) {
        $v = ''
        if ($map.Contains($f.Key)) { $v = $map[$f.Key] }
        if ([string]::IsNullOrWhiteSpace($v)) {
            $missing++
            Write-Host ('  [ ] ' + $f.Label.PadRight(28) + 'missing') -ForegroundColor DarkYellow
        }
        else {
            Write-Host ('  [x] ' + $f.Label.PadRight(28) + (Format-Masked $v $f.Secret)) -ForegroundColor Green
        }
    }
    Write-Host ''
    if ($missing -eq 0) {
        Write-Host '  All set. Tell Claude to go.' -ForegroundColor Green
    }
    else {
        Write-Host ("  $missing still needed. Re-run this script whenever you have one.") -ForegroundColor Yellow
    }

    Write-Host ''
    Write-Host '  Terminal logins' -ForegroundColor Cyan
    Write-Host '  ---------------' -ForegroundColor Cyan
    # File-based checks on purpose: invoking these CLIs just to probe them makes
    # PowerShell 5.1 treat their stderr banner as a terminating error.
    # gh keeps its token in the Windows keyring, so a file check false-negatives.
    # cmd /c swallows the CLI banner that would otherwise blow up PowerShell 5.1.
    $checks = @(
        @{ n = 'Netlify'; c = 'netlify'; path = (Join-Path $env:USERPROFILE '.netlify\config.json'); needle = 'auth'; probe = 'netlify api getCurrentUser'; fix = 'netlify login  (or paste NETLIFY_AUTH_TOKEN)' },
        @{ n = 'GitHub'; c = 'gh'; path = (Join-Path $env:USERPROFILE '.config\gh\hosts.yml'); needle = 'oauth_token'; probe = 'gh auth status'; fix = 'gh auth login' }
    )
    foreach ($chk in $checks) {
        $installed = Get-Command $chk.c -ErrorAction SilentlyContinue
        $loggedIn = $false
        if ($chk.n -eq 'Netlify' -and -not [string]::IsNullOrWhiteSpace($map['NETLIFY_AUTH_TOKEN'])) {
            $loggedIn = $true
        }
        if ((-not $loggedIn) -and $installed) {
            cmd /c "$($chk.probe) >nul 2>&1"
            if ($LASTEXITCODE -eq 0) { $loggedIn = $true }
        }
        if ((-not $loggedIn) -and (Test-Path -LiteralPath $chk.path)) {
            $raw = Get-Content -LiteralPath $chk.path -Raw -ErrorAction SilentlyContinue
            if ($raw -and $raw -match $chk.needle) { $loggedIn = $true }
        }
        if ($loggedIn) {
            Write-Host ('  [x] ' + $chk.n.PadRight(28) + 'logged in') -ForegroundColor Green
        }
        elseif (-not $installed) {
            Write-Host ('  [ ] ' + $chk.n.PadRight(28) + 'CLI not installed') -ForegroundColor DarkYellow
        }
        else {
            Write-Host ('  [ ] ' + $chk.n.PadRight(28) + 'run:  ' + $chk.fix) -ForegroundColor DarkYellow
        }
    }
    Write-Host ''
}

if ($Status) { Show-Status $values; exit 0 }

# ---------------------------------------------------------------- guided prompts

Write-Host ''
Write-Host '  Solstice FDE setup' -ForegroundColor Cyan
Write-Host '  Paste each value and press Enter. Blank skips it.' -ForegroundColor Gray
Write-Host '  Type  q  at any prompt to stop. Everything is saved as you go.' -ForegroundColor Gray

foreach ($f in $fields) {
    $existing = ''
    if ($values.Contains($f.Key)) { $existing = $values[$f.Key] }

    if ($Only -and $Only.Count -gt 0) {
        # Targeted mode: ask only for the named keys, and always re-ask them.
        if ($Only -notcontains $f.Key) { continue }
    }
    elseif ((-not $Force) -and (-not [string]::IsNullOrWhiteSpace($existing))) { continue }

    Write-Host ''
    Write-Host ('  ' + $f.Label) -ForegroundColor White
    Write-Host ('     find it:  ' + $f.Where) -ForegroundColor DarkGray
    Write-Host ('     note:     ' + $f.Note) -ForegroundColor DarkGray
    if (-not [string]::IsNullOrWhiteSpace($existing)) {
        Write-Host ('     current:  ' + (Format-Masked $existing $f.Secret)) -ForegroundColor DarkGray
    }

    $accepted = $false
    while (-not $accepted) {
        $entry = Read-Host '     paste'
        if ($null -eq $entry) { $entry = '' }
        $entry = $entry.Trim()

        if ($entry -eq 'q') { Write-Host ''; Write-Host '  Stopped. Progress saved.' -ForegroundColor Yellow; Show-Status (Read-EnvFile); exit 0 }
        if ($entry -eq '') { Write-Host '     skipped' -ForegroundColor DarkYellow; $accepted = $true; continue }

        if ($f.Key -eq 'DEMO_PHONE') { $entry = Format-Phone $entry }

        if ($entry -notmatch $f.Pattern) {
            Write-Host "     that does not look right ($($f.Note))." -ForegroundColor Red
            $again = Read-Host '     use it anyway? (y/N)'
            if ($again -ne 'y') { continue }
        }

        $values[$f.Key] = $entry
        Write-EnvFile $values
        Write-Host ('     saved:    ' + (Format-Masked $entry $f.Secret)) -ForegroundColor Green
        $accepted = $true
    }
}

Write-EnvFile $values
Show-Status (Read-EnvFile)
