/**
 * THE NET-NEW SERVICE: same-day availability by property, date and room class.
 *
 * WHY IT EXISTS (stated assumption, repeated in agent/sol.md and the README):
 * Policies 1 and 6 both hang on same-day availability in different words -- Policy 1 says
 * "based on same-day room availability", Policy 6 "based on same-day inventory" --
 * but the provided exports contain no inventory-by-date anywhere. Room COUNTS
 * exist on the properties export; OCCUPANCY on a given night does not. Without
 * this service the agent would have to invent availability every time a guest
 * asks for a late checkout or an upgrade, which is exactly what the brief
 * forbids. So we declare the gap, build a simulated service behind a clean
 * interface, and label every answer it produces as simulated.
 *
 * Properties of the simulation, on purpose:
 *  - DETERMINISTIC. The same property + date + room class always yields the same
 *    number, so a demo is reproducible and a supervisor sees the same figure the
 *    guest was told.
 *  - BOUNDED BY REAL DATA. Room counts come from the property record, never from
 *    the simulation.
 *  - OVERRIDABLE AT RUNTIME. `AVAILABILITY_MODE` and `AVAILABILITY_OVERRIDES` let
 *    Enrique force a sold-out house mid-demo without a redeploy.
 *
 * THE SEAM: replace `sameDayAvailability` with a PMS call (Opera, Cloudbeds,
 * Mews) and nothing else in the tool layer changes.
 */
import type { Property } from '../../../shared/types'
import { ROOM_CLASS_LADDER, type RoomClass } from './rules'

export type AvailabilityMode = 'simulated' | 'sold_out' | 'wide_open'

export interface AvailabilitySnapshot {
  property_code: string
  date: string
  room_class: string
  total_rooms: number
  rooms_available: number
  occupancy_pct: number
  /** Always present, always honest. */
  provenance: 'simulated_inventory_service'
  mode: AvailabilityMode
  assumption: string
}

const ASSUMPTION =
  'Simulated inventory. The provided exports contain room counts but no inventory-by-date, so same-day availability is generated by a declared stand-in service, not read from a PMS.'

// ------------------------------------------------------------------ runtime knobs

function currentMode(): AvailabilityMode {
  const raw = (process.env.AVAILABILITY_MODE ?? 'simulated').trim().toLowerCase()
  if (raw === 'sold_out' || raw === 'wide_open') return raw
  return 'simulated'
}

/**
 * `AVAILABILITY_OVERRIDES` is JSON keyed by `PROPERTY|DATE|ROOM CLASS`, or the
 * looser `PROPERTY|DATE`, mapping to a number of rooms available. Lets a specific
 * demo beat be pinned without touching code.
 *   {"SOL-DEN|2026-07-23|Suite": 0}
 */
function overrideFor(propertyCode: string, date: string, roomClass: string): number | null {
  const raw = process.env.AVAILABILITY_OVERRIDES
  if (!raw) return null
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    return null
  }
  if (typeof parsed !== 'object' || parsed === null) return null
  const table = parsed as Record<string, unknown>
  for (const key of [`${propertyCode}|${date}|${roomClass}`, `${propertyCode}|${date}`]) {
    const v = table[key]
    if (typeof v === 'number' && Number.isFinite(v)) return Math.max(0, Math.floor(v))
  }
  return null
}

// ------------------------------------------------------------ deterministic noise

/** FNV-1a. Small, fast, stable across runs and platforms. */
function hash32(input: string): number {
  let h = 0x811c9dc5
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h >>> 0
}

function unitInterval(input: string): number {
  return hash32(input) / 0xffffffff
}

// ---------------------------------------------------------------- room inventory

/**
 * `Property.inventory` is a `Record<string, number>` built upstream from the
 * per-class columns on the CSV. We do not control the exact key spelling the data
 * layer chose, so try the plausible ones rather than hard-failing on a hyphen.
 */
export function roomsOfClass(property: Property, roomClass: string): number | null {
  const inventory = property.inventory ?? {}
  const candidates = [
    roomClass,
    roomClass.toLowerCase(),
    roomClass.replace(/\s+/g, '_').toLowerCase(),
    `${roomClass.replace(/\s+/g, '_').toLowerCase()}_rooms`,
    roomClass.replace(/\s+/g, '').toLowerCase(),
  ]
  for (const key of candidates) {
    const v = inventory[key]
    if (typeof v === 'number' && Number.isFinite(v)) return v
  }
  // Case-insensitive, separator-insensitive last pass.
  const wanted = roomClass.replace(/[^a-z0-9]/gi, '').toLowerCase()
  for (const [k, v] of Object.entries(inventory)) {
    const normalized = k.replace(/_rooms$/i, '').replace(/[^a-z0-9]/gi, '').toLowerCase()
    if (normalized === wanted && typeof v === 'number' && Number.isFinite(v)) return v
  }
  return null
}

// ------------------------------------------------------------------- the service

/**
 * Same-day availability for one room class. `roomClass` may be any string; when
 * it is not on the ladder we fall back to the property's own inventory key, and
 * to a proportional share of total rooms only as a last resort.
 */
export function sameDayAvailability(property: Property, date: string, roomClass: string): AvailabilitySnapshot {
  const mode = currentMode()

  let total = roomsOfClass(property, roomClass)
  if (total === null) {
    // Unknown class: assume an even split of the house across the ladder so the
    // number is at least bounded by real total_rooms.
    total = Math.max(1, Math.floor((property.total_rooms || 0) / ROOM_CLASS_LADDER.length))
  }

  const forced = overrideFor(property.property_code, date, roomClass)
  if (forced !== null) {
    const available = Math.min(forced, total)
    return {
      property_code: property.property_code,
      date,
      room_class: roomClass,
      total_rooms: total,
      rooms_available: available,
      occupancy_pct: total > 0 ? Math.round(((total - available) / total) * 100) : 100,
      provenance: 'simulated_inventory_service',
      mode,
      assumption: `${ASSUMPTION} This figure was pinned by AVAILABILITY_OVERRIDES for the demo.`,
    }
  }

  let available: number
  if (mode === 'sold_out') {
    available = 0
  } else if (mode === 'wide_open') {
    available = total
  } else {
    // Occupancy between 55% and 100%, weighted so scarce classes (suites) run
    // tighter than the base classes. Deterministic in (property, date, class).
    const seed = unitInterval(`${property.property_code}|${date}|${roomClass}`)
    const scarcity = total <= 20 ? 0.12 : 0
    const occupancy = Math.min(1, 0.55 + seed * 0.45 + scarcity)
    available = Math.max(0, Math.round(total * (1 - occupancy)))
  }

  return {
    property_code: property.property_code,
    date,
    room_class: roomClass,
    total_rooms: total,
    rooms_available: available,
    occupancy_pct: total > 0 ? Math.round(((total - available) / total) * 100) : 100,
    provenance: 'simulated_inventory_service',
    mode,
    assumption: ASSUMPTION,
  }
}

/**
 * House-wide occupancy for a date, used by the discretionary late-checkout and
 * early-check-in gates. Returns a fraction in [0, 1].
 */
export function houseOccupancy(property: Property, date: string): number {
  const mode = currentMode()
  if (mode === 'sold_out') return 1
  if (mode === 'wide_open') return 0.4

  let total = 0
  let available = 0
  for (const roomClass of ROOM_CLASS_LADDER) {
    const snap = sameDayAvailability(property, date, roomClass)
    total += snap.total_rooms
    available += snap.rooms_available
  }
  if (total <= 0) return 1
  return Math.min(1, Math.max(0, (total - available) / total))
}

/** Availability across every class on the ladder, for the upgrade decision. */
export function availabilityByClass(property: Property, date: string): Record<RoomClass, AvailabilitySnapshot> {
  const out = {} as Record<RoomClass, AvailabilitySnapshot>
  for (const roomClass of ROOM_CLASS_LADDER) {
    out[roomClass] = sameDayAvailability(property, date, roomClass)
  }
  return out
}

export const AVAILABILITY_ASSUMPTION = ASSUMPTION
