/**
 * A sample transcript and the script that captures it must agree about what it is.
 *
 * `transcripts/refund-outside-window.md` was titled *"Refund request outside the service recovery
 * window"*. The transcript underneath it is a **Policy 2** cancellation charge: the guest cancelled
 * a stay 36 hours *inside* the 72-hour window and was charged a night. Policy 5 — the service
 * recovery window, 72 hours *after checkout* — never appears in it, and its clock never started,
 * because there was no stay and no in-stay problem. The title also pointed the wrong way: Policy 2
 * charges for cancelling **inside** its window, which is exactly what happened.
 *
 * The phrase was almost certainly lifted from Policy 15, which lists *"refund requests outside the
 * service recovery window"* as an escalation trigger, and from `agent/sol.md` §8, where that summary
 * string is used correctly for R55012 — a real refund request 312 hours after checkout. Right
 * sentence, wrong transcript.
 *
 * A sample transcript is a named deliverable of the brief, and the people reading it wrote the
 * policy document. This is the cheapest possible thing for them to catch.
 *
 * What makes it worth a guard rather than a one-line fix is where the title lives: **twice**. Every
 * transcript in `SCENARIOS` is generated by `scripts/capture-transcripts.mjs`, which writes the H1
 * and the "What this shows" line from its own case list. Fixing the markdown alone would leave the
 * wrong title in the generator, ready to come back the next time anyone re-captures — and all four
 * agreed before this change, so nothing would have complained.
 *
 * The generator is parsed as text, not imported: it runs its capture at module scope, reads `.env`
 * and calls production. A guard must never be the thing that makes a network request.
 */
import { existsSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const repoRoot = resolve(__dirname, '../../../..')
const GENERATOR = 'scripts/capture-transcripts.mjs'

type Scenario = { slug: string; title: string; shows: string }

function scenarios(): { parsed: Scenario[]; declared: number } {
  const src = readFileSync(join(repoRoot, GENERATOR), 'utf8')
  const parsed: Scenario[] = []
  for (const m of src.matchAll(/slug: '([^']+)',\s*\n\s*title: '([^']+)',\s*\n\s*shows: '([^']+)',/g)) {
    parsed.push({ slug: m[1], title: m[2], shows: m[3] })
  }
  return { parsed, declared: (src.match(/^\s*slug: '/gm) ?? []).length }
}

describe('captured transcripts and the script that captures them', () => {
  it('parses every scenario the generator declares, so a quoting change cannot silently skip one', () => {
    const { parsed, declared } = scenarios()
    expect(declared).toBeGreaterThanOrEqual(4)
    expect(
      parsed.length,
      `${GENERATOR} declares ${declared} scenarios but this test could only parse ${parsed.length}. ` +
        `A title or slug containing an apostrophe would do that, and the unparsed ones would go ` +
        `unchecked — widen the pattern rather than leaving them out.`,
    ).toBe(declared)
  })

  it.each(scenarios().parsed)('$slug is titled the same in both places', ({ slug, title, shows }) => {
    const file = `transcripts/${slug}.md`
    expect(existsSync(join(repoRoot, file)), `${GENERATOR} writes ${file}, which is missing`).toBe(true)

    const text = readFileSync(join(repoRoot, file), 'utf8')
    const h1 = text.split(/\r?\n/)[0].replace(/^#\s*/, '').trim()
    expect(
      h1,
      `${file} is titled ${JSON.stringify(h1)} but ${GENERATOR} would write ` +
        `${JSON.stringify(title)}. Re-capturing would overwrite the title in the deliverable.`,
    ).toBe(title)

    const line = text.match(/\*\*What this shows:\*\*\s*(.+)/)
    expect(line, `${file} has no "What this shows" line`).not.toBeNull()
    expect(
      line?.[1].trim(),
      `${file}'s "What this shows" line has drifted from the one ${GENERATOR} would write.`,
    ).toBe(shows)
  })
})

/**
 * The claim a transcript's title makes about policy must match the policy it actually cites.
 *
 * Narrower than it sounds, and deliberately so: only the two 72-hour windows, which are the pair the
 * package already got backwards once. Policy 2 runs *before check-in*, Policy 5 runs *after
 * checkout*, and a transcript that cites one while its title names the other is wrong in the way
 * that is hardest to see and easiest for the brief's authors to spot.
 */
describe('transcript titles against the policies the transcript cites', () => {
  it('no transcript claims service recovery unless it cites Policy 5', () => {
    const problems: string[] = []
    for (const { slug } of scenarios().parsed) {
      const text = readFileSync(join(repoRoot, `transcripts/${slug}.md`), 'utf8')
      const h1 = text.split(/\r?\n/)[0]
      if (!/service recovery/i.test(h1)) continue
      if (!/Policy 5\b/.test(text)) {
        problems.push(
          `transcripts/${slug}.md is titled ${JSON.stringify(h1.replace(/^#\s*/, ''))}, but the ` +
            `transcript never cites Policy 5 — the service recovery window. Check which policy it ` +
            `actually applies before keeping that title.`,
        )
      }
    }
    expect(problems, problems.join('\n')).toEqual([])
  })
})
