// Route shell. Owned by the foundation, not by feature agents.
// Feature agents fill in the page modules; they do not edit this file.
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom'
import ErrorBoundary from '@/components/ErrorBoundary'
import Landing from '@/pages/Landing'
import Login from '@/pages/Login'
import RequireRole from '@/components/RequireRole'
import SupervisorDashboard from '@/pages/admin/SupervisorDashboard'
import SessionDetail from '@/pages/admin/SessionDetail'
import GroupInbox from '@/pages/admin/GroupInbox'
import InquiryDetail from '@/pages/admin/InquiryDetail'
import AdminHome from '@/pages/admin/AdminHome'
import BackendMap from '@/pages/admin/BackendMap'

export default function App() {
  return (
    <BrowserRouter>
      <ErrorBoundary>
      <Routes>
        {/* guest */}
        <Route path="/" element={<Landing />} />
        <Route path="/login" element={<Login />} />

        {/* concierge supervisor */}
        <Route element={<RequireRole allow={['concierge', 'admin']} />}>
          <Route path="/admin/sessions" element={<SupervisorDashboard />} />
          <Route path="/admin/sessions/:id" element={<SessionDetail />} />
        </Route>

        {/* group sales */}
        <Route element={<RequireRole allow={['group_sales', 'admin']} />}>
          <Route path="/admin/inquiries" element={<GroupInbox />} />
          <Route path="/admin/inquiries/:id" element={<InquiryDetail />} />
        </Route>

        {/* super admin */}
        <Route element={<RequireRole allow={['admin']} />}>
          <Route path="/admin" element={<AdminHome />} />
          <Route path="/admin/backend" element={<BackendMap />} />
        </Route>

        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
      </ErrorBoundary>
    </BrowserRouter>
  )
}
